#include "main.h"

struct preability_i
{
	ability_s				key;
	char					value;
};
struct prerequisit_i
{
	adat<feat_s, 8>			feats;
	preability_i			abilities[2];
	char					base_attack_bonus;
};
static struct feat_i
{
	const char*				name[2];
	talent_s				tree;
	prerequisit_i			require;
} feat_data[] = {
	{{"", ""}},
	//
	{{"Adept negotiator"}, JediConsular},
	{{"Force persuasion"}, JediConsular, {{1, {AdeptNegotiator}}}},
	{{"Master negotiator"}, JediConsular, {{1, {AdeptNegotiator}}}},
	{{"Skilled advisor"}, JediConsular},
	{{"Acrobatic recovery"}, JediGuardian},
	{{"Battle Meditation"}, JediGuardian},
	{{"Elusive Target"}, JediGuardian},
	{{"Force Intuition"}, JediGuardian},
	{{"Resilience"}, JediGuardian},
	{{"Clear Mind"}, JediSentinel},
	{{"Dark Side Sence"}, JediSentinel},
	{{"Dark Side Scourge"}, JediSentinel, {{1, {DarkSideSence}}}},
	{{"Force Haze"}, JediSentinel},
	{{"Resist Dark Side"}, JediSentinel, {{1, {DarkSideSence}}}},
	{{"Block"}, LightsaberCombat},
	{{"Deflect"}, LightsaberCombat},
	{{"Lightsaber Defence"}, LightsaberCombat},
	{{"Lightsaber Defence II"}, LightsaberCombat, {{1, {LightsaberDefence}}}},
	{{"Lightsaber Defence III"}, LightsaberCombat, {{1, {LightsaberDefenceII}}}},
	{{"Weapon Specialization (Lightsaber)"}, LightsaberCombat},
	{{"Lightsaber Throw"}, LightsaberCombat},
	{{"Redirect Shot"}, LightsaberCombat, {{1, {Deflect}}, {}, 5}},
	//
	{{"Presence"}, Influence},
	{{"Demand Surrender"}, Influence, {{1, {Presence}}}},
	{{"Improved Weaken Resolve"}, Influence, {{2, {Presence, WeakenResolve}}}},
	{{"Weaken Resolve"}, Influence, {{1, {Presence}}}},
	{{"Bolster Ally"}, Inspiration},
	{{"Ignite Ferver"}, Inspiration, {{2, {BolsterAlly, InspireConfidence}}}},
	{{"Inspire Confidence"}, Inspiration},
	{{"Inspire Haste"}, Inspiration},
	{{"Inspire Zeal"}, Inspiration, {{3, {BolsterAlly, InspireConfidence, IgniteFerver}}}},
	{{"Born Leader"}, Leadership},
	{{"Coordinate"}, Leadership},
	{{"Distant Command"}, Leadership},
	{{"Fearless Leader"}, Leadership},
	{{"Rally"}, Leadership},
	{{"Trust"}, Leadership},
	{{"Connections"}, Lineage},
	{{"Educated"}, Lineage},
	{{"Spontaneous Skill"}, Lineage, {{1, {Educated}}}},
	{{"Wealth"}, Lineage},
	//
	{{"Acrobatic Strike"}, General},
	{{"Armour Proficience Light"}, General},
	{{"Armour Proficience Medium"}, General},
	{{"Armour Proficience Heavy"}, General},
	{{"Bantha Rush"}, General},
	{{"Burst Fire"}, General},
	{{"Careful Shoot"}, General},
	{{"Charging Fire"}, General},
	{{"Cleave"}, General},
	{{"Combat Reflexes"}, General},
	{{"Coordinated Attack"}, General},
	{{"Crush"}, General},
	{{"Cybernetic Surgery"}, General},
	{{"Deadeye"}, General},
	{{"Dodge"}, General},
	{{"DoubleAttack"}, General},
	{{"Dreadful Rage"}, General},
	{{"DualWeapon Mastery"}, General},
	{{"Extra Rage"}, General},
	{{"Extra Second Wind"}, General},
	{{"Far Shoot"}, General},
	{{"Force Boon"}, General},
	{{"Force Sensitivity"}, General},
	{{"Force Training"}, General},
	{{"Improved Charge"}, General},
	{{"Improved Defences"}, General},
	{{"Improved Disarm"}, General},
	{{"Improved Damage Threshold"}, General},
	{{"Linguist"}, General},
	{{"Martial Arts"}, General},
	{{"Martial Arts II"}, General},
	{{"Martial Arts III"}, General},
	{{"Melee Defence"}, General},
	{{"Mighty Swing"}, General},
	{{"Mobility"}, General},
	{{"Pin"}, General},
	{{"Point-blank Shoot"}, General},
	{{"Power Attack"}, General},
	{{"Powerful Charge"}, General},
	{{"Precise Shoot"}, General},
	{{"Quick Draw"}, General},
	{{"Rapid Shoot"}, General},
	{{"Rapid Strike"}, General},
	{{"Running Attack"}, General},
	{{"Shake it off"}, General},
	{{"Sniper"}, General},
	{{"Skill focus (Acrobatic)"}, General},
	{{"Skill focus (Climb)"}, General},
	{{"Skill focus (Deception)"}, General},
	{{"Skill focus (Endurance)"}, General},
	{{"Skill focus (Gather Information)"}, General},
	{{"Skill focus (Initiative)"}, General},
	{{"Skill focus (Jump)"}, General},
	{{"Skill focus (Buerocracy)"}, General},
	{{"Skill focus (Galactic Lore)"}, General},
	{{"Skill focus (Life Sciences)"}, General},
	{{"Skill focus (Physical Sciences)"}, General},
	{{"Skill focus (Social Sciences)"}, General},
	{{"Skill focus (Tactics)"}, General},
	{{"Skill focus (Technology)"}, General},
	{{"Skill focus (Mechanics)"}, General},
	{{"Skill focus (Perception)"}, General},
	{{"Skill focus (Persuasion)"}, General},
	{{"Skill focus (Pilot)"}, General},
	{{"Skill focus (Ride)"}, General},
	{{"Skill focus (Stealth)"}, General},
	{{"Skill focus (Survival)"}, General},
	{{"Skill focus (Swim)"}, General},
	{{"Skill focus (Treat Injury)"}, General},
	{{"Skill focus (Use Computer)"}, General},
	{{"Skill focus (Use Force)"}, General},
	{{"Strong in the Force"}, General},
	{{"Surgical Expertise"}, General},
	{{"Throw"}, General},
	{{"Toughness"}, General},
	{{"Trip"}, General},
	{{"Triple attack"}, General},
	{{"Triple critical"}, General},
	{{"Vehicular combat"}, General},
	{{"Weapon finess"}, General},
	{{"Weapon proficiency (Advanced Melee Weapons)"}, General},
	{{"Weapon proficiency (Exotic Weapons)"}, General},
	{{"Weapon proficiency (Heavy Weapons)"}, General},
	{{"Weapon proficiency (Lightsabers)"}, General},
	{{"Weapon proficiency (Pistols)"}, General},
	{{"Weapon proficiency (Rifles)"}, General},
	{{"Weapon proficiency (Simple Weapons)"}, General},
	{{"Whirlwind attack"}, General},
	//
	{{"Acrobatic", "Акробатика"}, Skills},
	{{"Climb", "Лазить"}, Skills},
	{{"Deception", "Обман"}, Skills},
	{{"Endurance", "Выносливость"}, Skills},
	{{"Gather Information", "Добывание информации"}, Skills},
	{{"Initiative", "Инициатива"}, Skills},
	{{"Jump", "Прыжки"}, Skills},
	{{"Buerocracy", "Бюрократия"}, Skills},
	{{"Galactic Lore", "Знание галактики"}, Skills},
	{{"Life Sciences", "Биологические науки"}, Skills},
	{{"Physical Sciences", "Физические науки"}, Skills},
	{{"Social Sciences", "Социальные науки"}, Skills},
	{{"Tactics", "Тактика"}, Skills},
	{{"Technology", "Технологии"}, Skills},
	{{"Mechanics", "Механика"}, Skills},
	{{"Perception", "Внимательность"}, Skills},
	{{"Persuasion", "Убеждение"}, Skills},
	{{"Pilot", "Пилот"}, Skills},
	{{"Ride", "Езда верхом"}, Skills},
	{{"Stealth", "Скрытность"}, Skills},
	{{"Survival", "Выживание"}, Skills},
	{{"Swim", "Плавание"}, Skills},
	{{"Treat Injury", "Лечить ранения"}, Skills},
	{{"Use Computer", "Использовать компьютер"}, Skills},
	{{"Use Force", "Использовать силу"}, Skills},
	//
	{{"Bonus Trained Skill", "Дополнительный навык"}, RacialFeat},
	{{"Bonus Feat", "Дополнительная особенность"}, RacialFeat},
	{{"Primitive", "Примитивный"}, RacialFeat},
	{{"Lowlight Vision", "Низкосветовое зрение"}, RacialFeat},
	{{"Darkvision", "Инфрозрение"}, RacialFeat},
	{{"Expert Swimmer", "Искусстный плавец"}, RacialFeat},
	{{"Expert Pilot", "Искусстный пилот"}, RacialFeat},
	{{"Expert Climber", "Паучье лазание"}, RacialFeat},
	{{"Sneaky", "Скрытный"}, RacialFeat},
	{{"Survival Instinct", "Инстинкт выживания"}, RacialFeat},
	{{"Intuitive Initiative", "Интуитивная инициатива"}, RacialFeat},
	{{"Keen Force Sence", "Острое чувство силы"}, RacialFeat},
	{{"Heighten Awareness", "Повышенная настороженность"}, RacialFeat},
	{{"Deceptive", "Искусстный лжец"}, RacialFeat},
	{{"Extraordinary Recuperation", "Ускоренная заживаемость ран"}, RacialFeat},
	{{"Hold Breath", "Задержка дыхания"}, RacialFeat},
	{{"Breath Underwater", "Дышит под водой"}, RacialFeat},
	{{"Bellow", "Рев"}, RacialFeat},
	{{"Limb Regeneration", "Регенерация конечностей"}, RacialFeat},
	{{"Natural Armour", "Натуральная броня"}, RacialFeat},
	{{"Iron Will", "Железная воля"}, RacialFeat},
	{{"Great Fortitude", "Огромная стойкость"}, RacialFeat},
	{{"Lighting Reflexes", "Молниеносные рефлексы"}, RacialFeat},
	{{"Superior Defences", "Превосходная защита"}, RacialFeat},
	{{"Rage", "Бешенство"}, RacialFeat},
	{{"Scent", "Нюх"}, RacialFeat},
};
assert_enum(feat, Scent);
getstr_enum(feat);